# -*- generated by 1.0.14 -*-
import da
PatternExpr_223 = da.pat.TuplePattern([da.pat.FreePattern('PROPOSAL'), da.pat.FreePattern('message'), da.pat.FreePattern('sender'), da.pat.FreePattern('senderId')])
PatternExpr_288 = da.pat.TuplePattern([da.pat.FreePattern('VOTE'), da.pat.FreePattern('result'), da.pat.FreePattern('senderId')])
PatternExpr_315 = da.pat.TuplePattern([da.pat.FreePattern('TXN'), da.pat.FreePattern('payload')])
_config_object = {'channel': 'fifo', 'clock': 'lamport'}
import mempool as mp
import main as mainmodule
from constants import *
import block as bl
import proposalMessage as propMsg

class Author(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_AuthorReceivedEvent_0', PatternExpr_223, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Author_handler_222]), da.pat.EventPattern(da.pat.ReceivedEvent, '_AuthorReceivedEvent_1', PatternExpr_288, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Author_handler_287]), da.pat.EventPattern(da.pat.ReceivedEvent, '_AuthorReceivedEvent_2', PatternExpr_315, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Author_handler_314])])

    def setup(self, validators, otherValidators, num, authorMap, **rest_428):
        super().setup(validators=validators, otherValidators=otherValidators, num=num, authorMap=authorMap, **rest_428)
        self._state.validators = validators
        self._state.otherValidators = otherValidators
        self._state.num = num
        self._state.authorMap = authorMap
        self._state.n = len(self._state.validators)
        self._state.num = self._state.num
        self._state.memPool = mp.MemPool()
        self._state.main = mainmodule.Main(self._state.num)

    def run(self):
        self.log('Author started')
        super()._label('_st_label_409', block=False)
        _st_label_409 = 0
        while (_st_label_409 == 0):
            _st_label_409 += 1
            if False:
                _st_label_409 += 1
            else:
                super()._label('_st_label_409', block=True)
                _st_label_409 -= 1

    def getNum(self):
        return self._state.num

    def createProposalMessage(self, payload):
        block = bl.Block(self._state.main.pacemaker.getCurrentRound(), self._id, payload)
        pm = propMsg.ProposalMessage(block)
        return pm

    def log(self, msg):
        prefix = (('[AUTHOR-' + str(self._state.num)) + '] ')
        self.output((prefix + msg))

    def _Author_handler_222(self, PROPOSAL, message, sender, senderId):
        self.log(('Received proposal message from proposer - ' + str(senderId)))
        status = self._state.main.processProposalMessage(message)
        newLeader = self._state.authorMap[((senderId + 1) % self._state.n)]
        if status:
            self.send((VOTE, True, self._state.num), to=newLeader)
        else:
            self.send((VOTE, False, self._state.num), to=newLeader)
        self.log('Vote sent to new leader')
    _Author_handler_222._labels = None
    _Author_handler_222._notlabels = None

    def _Author_handler_287(self, VOTE, result, senderId):
        self.log(('Received vote message from - ' + str(senderId)))
        self.log(('Result received - ' + str(result)))
    _Author_handler_287._labels = None
    _Author_handler_287._notlabels = None

    def _Author_handler_314(self, TXN, payload):
        self._state.memPool.addTransaction(payload)
        self.log('Added transaction to mempool')
        if ((self._state.num == 0) and (self._state.main.pacemaker.getCurrentRound() == 0)):
            self.log('num == 0 and self.main.pacemaker.getCurrentRound() == 0')
            proposalMessage = self.createProposalMessage(payload)
            self.log(('Created proposal message - ' + str(proposalMessage)))
            self.send((PROPOSAL, proposalMessage, self._id, self._state.num), to=self._state.validators)
            self.log('Sent proposal message to all validators')
    _Author_handler_314._labels = None
    _Author_handler_314._notlabels = None
