# -*- generated by 1.0.14 -*-
import da
_config_object = {'channel': 'fifo', 'clock': 'lamport'}
import yaml
import logging
authorda = da.import_da('author')
clientda = da.import_da('client')
cfgPath = 'config/config.yaml'

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        with open(cfgPath, 'r') as stream:
            try:
                cfg = yaml.safe_load(stream)
                print(cfg)
            except yaml.YAMLError as exc:
                print(exc)
        self.output('[ENGINE] Config read from ', cfgPath)
        clients = self.new(clientda.Client, num=cfg['clientCount'])
        validators = self.new(authorda.Author, num=cfg['n'])
        self.output('[ENGINE] Validators created.')
        vNumber = 0
        authorMap = {}
        print('[ENGINE]: first v loop')
        for v in validators:
            print(str(v))
            authorMap[vNumber] = v
            vNumber += 1
        print('[ENGINE]: second v loop')
        vNumber = 0
        for v in validators:
            print(str(v))
            self._setup(v, (validators, (validators - {v}), vNumber, authorMap))
            vNumber += 1
        self.output('[ENGINE] Validators setup done.')
        for c in clients:
            self._setup(c, (validators,))
        self.output('[ENGINE] Client setup done.')
        self._start(validators)
        self._start(clients)
        super()._label('_st_label_313', block=False)
        _st_label_313 = 0
        while (_st_label_313 == 0):
            _st_label_313 += 1
            if False:
                _st_label_313 += 1
            else:
                super()._label('_st_label_313', block=True)
                _st_label_313 -= 1
