# -*- generated by 1.0.14 -*-
import da
PatternExpr_187 = da.pat.TuplePattern([da.pat.FreePattern('TXN'), da.pat.FreePattern('data')])
_config_object = {'channel': 'fifo', 'clock': 'lamport'}
import logging
import mempool as mp
from constants import *

class Author(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_AuthorReceivedEvent_0', PatternExpr_187, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Author_handler_186])])

    def setup(self, otherValidators, num, **rest_230):
        super().setup(otherValidators=otherValidators, num=num, **rest_230)
        self._state.otherValidators = otherValidators
        self._state.num = num
        self._state.memPool = mp.MemPool()

    def run(self):
        self.log('Replica started')
        super()._label('_st_label_211', block=False)
        _st_label_211 = 0
        while (_st_label_211 == 0):
            _st_label_211 += 1
            if False:
                _st_label_211 += 1
            else:
                super()._label('_st_label_211', block=True)
                _st_label_211 -= 1

    def log(self, msg):
        prefix = (('[REPLICA-' + str(self._state.num)) + '] ')
        self.output((prefix + msg))

    def _Author_handler_186(self, TXN, data):
        self._state.memPool.addTransaction(data)
        self.log('Added transaction to mempool')
    _Author_handler_186._labels = None
    _Author_handler_186._notlabels = None
