# -*- generated by 1.0.14 -*-
import da
PatternExpr_182 = da.pat.TuplePattern([da.pat.FreePattern('COMMITTED'), da.pat.FreePattern('c'), da.pat.FreePattern('p')])
_config_object = {'channel': 'fifo', 'clock': 'lamport'}
import logging
from constants import *
from transaction import *

class Client(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_0', PatternExpr_182, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_181])])

    def setup(self, validators, **rest_232):
        super().setup(validators=validators, **rest_232)
        self._state.validators = validators
        self._state.txnNumber = 0

    def run(self):
        self.output('[CLIENT] Client started')
        self.send((TXN, self.nextTransaction()), to=self._state.validators)
        self.output('[CLIENT] Sent transactions to all validators')
        self.output('[CLIENT] Waiting...')
        super()._label('_st_label_230', block=False)
        _st_label_230 = 0
        while (_st_label_230 == 0):
            _st_label_230 += 1
            if False:
                _st_label_230 += 1
            else:
                super()._label('_st_label_230', block=True)
                _st_label_230 -= 1

    def nextTransaction(self):
        transaction = Transaction(('Transaction - ' + str(self._state.txnNumber)))
        self._state.txnNumber += 1
        return transaction

    def _Client_handler_181(self, COMMITTED, c, p):
        print('Transaction committed by process - ', p)
    _Client_handler_181._labels = None
    _Client_handler_181._notlabels = None
