# -*- generated by 1.0.14 -*-
import da
_config_object = {}

class Block():

    def __init__(self, author, round, payload, qc, block_id):
        self.author = author
        self.round = round
        self.payload = payload
        self.qc = qc
        self.block_id = block_id
