# -*- generated by 1.0.14 -*-
import da
PatternExpr_228 = da.pat.FreePattern('message')
PatternExpr_232 = da.pat.FreePattern('node')
_config_object = {}
Transaction = da.import_da('transaction')

class Client(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_0', PatternExpr_228, sources=[PatternExpr_232], destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_227])])

    def setup(self, nodes, client_id, **rest_237):
        super().setup(nodes=nodes, client_id=client_id, **rest_237)
        self._state.nodes = nodes
        self._state.client_id = client_id
        self._state.transaction_id = (- 1)

    def run(self):
        self.output('[CLIENT] Starting Client....')
        txn = self.initiate_new_transaction()
        msg = txn.to_string()
        self.send(('TXN', txn), to=self._state.nodes)
        self.output('[CLIENT] Initiated transaction sent to all nodes. Waiting for a reply....')
        super()._label('_st_label_223', block=False)
        _st_label_223 = 0
        while (_st_label_223 == 0):
            _st_label_223 += 1
            if False:
                _st_label_223 += 1
            else:
                super()._label('_st_label_223', block=True)
                _st_label_223 -= 1

    def initiate_new_transaction(self):
        self._state.transaction_id += 1
        curr_trans = Transaction.Transaction(self._state.transaction_id, self._state.client_id, 2)
        return curr_trans

    def _Client_handler_227(self, message, node):
        self.output('[Client] Received Message', message)
    _Client_handler_227._labels = None
    _Client_handler_227._notlabels = None
