# -*- generated by 1.0.14 -*-
import da
_config_object = {}

class LeaderElection():
    F = 1

    def __init__(self, nodesDict, window_size, exclude_size, reputation_leaders):
        self.nodesDict = nodesDict
        self.window_size = window_size
        self.exclude_size = exclude_size
        self.reputation_leaders = reputation_leaders

    def get_leader(self, current_round):
        print('[Leader-Election] Get_Leader for round [{}]'.format(current_round))
        return self.round_robin_leader(current_round)

    def round_robin_leader(self, current_round):
        x = (current_round // 2)
        leader = (x % len(self.nodesDict))
        print('[Leader-Election] Round-Robin Leader: [{}]'.format(leader))
        return leader
