# -*- generated by 1.0.14 -*-
import da
_config_object = {}

class Ledger():

    def __init__(self):
        self.a = 0

    def speculate(self, prev_block_id, block_id, txns):
        pass

    def pending_state(self, block_id):
        return 0

    def commit(self, block_id):
        pass

    def committed_block(self, block_id):
        pass
