# -*- generated by 1.0.14 -*-
import da
_config_object = {'channel': 'fifo', 'clock': 'lamport'}
import json
import logging
author = da.import_da('test/author')
client = da.import_da('test/client')
cfgPath = 'config/config.json'

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        with open('config.json') as json_file:
            data = json.load(json_file)
        print(data['initial_leader'])
