# -*- generated by 1.0.14 -*-
import da
_config_object = {}
from block_tree import BlockTree

class Pacemaker():

    def __init__(self, current_round, last_round_tc, pending_timeouts, block_tree):
        self.current_round = current_round
        self.last_round_tc = last_round_tc
        self.pending_timeouts = pending_timeouts
        self.block_tree = block_tree

    def stop_timer(self, current_round):
        pass

    def start_timer(self, new_round):
        self.stop_timer(self.current_round)
        self.current_round = new_round

    def advance_round_tc(self, tc):
        if ((tc is None) or (tc.round < self.current_round)):
            return False
        self.last_round_tc = tc
        self.start_timer((tc.round + 1))
        return True

    def advance_round_qc(self, qc):
        print('Pacemaker - Advance Round QC')
        if (not (qc is None)):
            if (qc.vote_info.round < self.current_round):
                return False
            last_round_tc = None
            self.start_timer((qc.vote_info.round + 1))
            return True

    def advance_round(self, round):
        print('Holaaaaa')
        pass
