# -*- generated by 1.0.14 -*-
import da
_config_object = {}

class ProposalMessage():

    def __init__(self, block, last_round_tc, high_commit_qc):
        self.block = block
        self.last_round_tc = last_round_tc
        self.high_commit_qc = high_commit_qc
