# -*- generated by 1.0.14 -*-
import da
_config_object = {}
# from constants import MessageType

class Transaction():

    def __init__(self, transaction_id, client_id, message_type):
        self.transaction_id = transaction_id
        self.client_id = client_id
        self.message_type = message_type

    def to_string(self):
        msg = ((('Transaction :' + str(self.transaction_id)) + ', initiated by client: ') + str(self.client_id))
        return msg

    def is_local_timeout_m(self):
        if (self.message_type == 1):
            return True
        return False

    def is_vote_m(self):
        if (self.message_type == 3):
            return True
        return False

    def is_proposal_m(self):
        if (self.message_type == 2):
            return True
        return False

    def is_timeout_m(self):
        if (self.message_type == 4):
            return True
        return False
